name: build
on:
  - pull_request
  - workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: current
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint:check
      - run: npm run build
        env:
          VITE_MAILERLITE_ACCOUNT_ID: ${{ secrets.VITE_MAILERLITE_ACCOUNT_ID }}
          VITE_MAILERLITE_FORM_ID: ${{ secrets.VITE_MAILERLITE_FORM_ID }}
      - if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
